package me.cortex.voxy.commonImpl;

import net.neoforged.api.distmarker.Dist;
import net.neoforged.fml.ModList;
import net.neoforged.fml.loading.FMLLoader;
import net.neoforged.fml.loading.FMLPaths;
import net.neoforged.fml.loading.LoadingModList;
import net.neoforged.neoforgespi.locating.IModFile;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.util.List;
import java.util.Properties;

/**
 * The single loader shim for the NeoForge port (brief contract C9).
 *
 * Every method is safe to call from a mixin static initialiser (i.e. before {@code ModList} exists) and on a
 * dedicated server: nothing in here touches client classes, and every NeoForge call is wrapped so a missing
 * loader (JMH / unit tests running voxy outside of Minecraft) degrades to a "not present" answer instead of an
 * exception.
 *
 * 1.21.1: replaces {@code FabricLoader.getInstance().isModLoaded / getConfigDir / getModContainer(..).getRootPaths}
 * and the fabric.mod.json "custom" block (commit / buildtime) that upstream read through {@code ModMetadata}.
 */
public final class PlatformUtil {
    public static final String MOD_ID = "voxy";
    public static final String UNKNOWN = "<UNKNOWN>";
    private static final String BUILD_PROPERTIES = "/voxy-build.properties";

    private PlatformUtil() {}

    //Build descriptor (generated by build.gradle processResources: keys version, commit, buildtime)
    private static final String VERSION;
    private static final String COMMIT;
    private static final String BUILD_TIME;
    static {
        String version = null;
        String commit = null;
        String buildTime = null;
        try (InputStream stream = PlatformUtil.class.getResourceAsStream(BUILD_PROPERTIES)) {
            if (stream != null) {
                var props = new Properties();
                props.load(stream);
                version = props.getProperty("version");
                commit = props.getProperty("commit");
                buildTime = props.getProperty("buildtime");
            }
        } catch (IOException | RuntimeException ignored) {
            //Fall through to the UNKNOWN defaults below
        }
        if (version == null || version.isBlank()) {
            //Fallback: the version declared in neoforge.mods.toml (available very early through LoadingModList)
            version = modVersionFromModList();
        }
        VERSION = (version == null || version.isBlank()) ? UNKNOWN : version.strip();
        COMMIT = (commit == null || commit.isBlank()) ? UNKNOWN : commit.strip();
        BUILD_TIME = (buildTime == null || buildTime.isBlank()) ? UNKNOWN : buildTime.strip();
    }

    private static String modVersionFromModList() {
        try {
            var modFile = LoadingModList.get() == null ? null : LoadingModList.get().getModFileById(MOD_ID);
            if (modFile == null) return null;
            return modFile.getMods().stream()
                    .filter(m -> MOD_ID.equals(m.getModId()))
                    .findFirst()
                    .map(m -> m.getVersion().toString())
                    .orElse(null);
        } catch (Throwable t) {
            return null;
        }
    }

    /** Mod version string ({@code 0.2.19-beta}), or {@link #UNKNOWN}. */
    public static String modVersion() {
        return VERSION;
    }

    /** Full git commit hash the jar was built from, or {@link #UNKNOWN}. */
    public static String commitHash() {
        return COMMIT;
    }

    /** Unix build timestamp (seconds) as written by the build, or {@link #UNKNOWN}. */
    public static String buildTime() {
        return BUILD_TIME;
    }

    /**
     * Whether a mod is present. Uses {@code ModList} once mods are constructed and falls back to
     * {@code LoadingModList} (populated during mod discovery, i.e. before any mixin is applied) so it can be used
     * from mixin plugins and static initialisers. Any loader failure means "not loaded".
     */
    public static boolean isModLoaded(String modId) {
        try {
            var modList = ModList.get();
            if (modList != null) {
                return modList.isLoaded(modId);
            }
        } catch (Throwable ignored) {
            //ModList not available yet, try the loading list
        }
        try {
            var loading = LoadingModList.get();
            return loading != null && loading.getModFileById(modId) != null;
        } catch (Throwable ignored) {
            return false;
        }
    }

    /** True when voxy itself is loaded by a mod loader (false when running voxy standalone, e.g. JMH/tests). */
    public static boolean isInMinecraft() {
        return isModLoaded(MOD_ID);
    }

    /** Equivalent of {@code FabricLoader.getConfigDir()}. */
    public static Path configDir() {
        return FMLPaths.CONFIGDIR.get();
    }

    /** Equivalent of {@code FabricLoader.getGameDir()}. */
    public static Path gameDir() {
        return FMLPaths.GAMEDIR.get();
    }

    /** Equivalent of {@code FabricLoader.getEnvironmentType() == EnvType.SERVER}; false when the loader is absent. */
    public static boolean isDedicatedServer() {
        try {
            return FMLLoader.getDist() == Dist.DEDICATED_SERVER;
        } catch (Throwable t) {
            return false;
        }
    }

    /** Equivalent of {@code FabricLoader.getEnvironmentType() == EnvType.CLIENT}; false when the loader is absent. */
    public static boolean isClient() {
        try {
            return FMLLoader.getDist() == Dist.CLIENT;
        } catch (Throwable t) {
            return false;
        }
    }

    private static IModFile modFile(String modId) {
        try {
            var modList = ModList.get();
            if (modList != null) {
                var info = modList.getModFileById(modId);
                if (info != null) return info.getFile();
            }
        } catch (Throwable ignored) {
            //ModList not available yet, try the loading list
        }
        try {
            var loading = LoadingModList.get();
            if (loading != null) {
                var info = loading.getModFileById(modId);
                if (info != null) return info.getFile();
            }
        } catch (Throwable ignored) {
        }
        return null;
    }

    /**
     * Equivalent of {@code FabricLoader.getModContainer(modId).get().getRootPaths()}: the root of the mod's
     * content as a {@link Path} that can be walked with {@code Files.list/Files.exists}. NeoForge exposes every mod
     * (a jar in production, a classes directory in dev) through a {@code SecureJar} whose root path is a union
     * filesystem path, so a single implementation covers both cases.
     */
    public static List<Path> modRootPaths(String modId) {
        var file = modFile(modId);
        if (file == null) return List.of();
        try {
            var root = file.getSecureJar().getRootPath();
            if (root != null) return List.of(root);
        } catch (Throwable ignored) {
        }
        try {
            //Older/odd loaders: findResource("") resolves the root of the mod file
            var root = file.findResource("");
            if (root != null) return List.of(root);
        } catch (Throwable ignored) {
        }
        return List.of();
    }

    /** First root path of voxy itself, or null when voxy is not loaded by a mod loader. */
    public static Path modRootPath() {
        var roots = modRootPaths(MOD_ID);
        return roots.isEmpty() ? null : roots.get(0);
    }

    /** Path of the mod file on disk (the jar, or the classes directory in dev), or null. */
    public static Path modFilePath(String modId) {
        var file = modFile(modId);
        if (file == null) return null;
        try {
            return file.getFilePath();
        } catch (Throwable t) {
            return null;
        }
    }
}
